modLoader = "javafml"
loaderVersion = "[36,)"
license = "Mulan Permissive Software License，Version 2"

[[mods]]
modId = "threebodysophon"
version = "${file.jarVersion}"
displayName = "Threebody Sophon"
logoFile = "threebodysophon.png"
credits = "XuFly 德尔"
authors = "XuFly"
description = '''
Mod Restores Sophon in Liu Tzuxin's famous science fiction novel "Three Bodies" (as far as possible)
'''

[[dependencies.threebodysophon]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.threebodysophon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
